version: '3.8'

services:
  web-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5000
    volumes:
      - .env.local:/app/.env.local
    restart: unless-stopped